/// Flutter icons TikiSdkIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TikiSdkIcons
///      fonts:
///       - asset: fonts/TikiSdkIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class TikiSdkIcons {
  TikiSdkIcons._();

  static const _kFontFam = 'TikiSdkIcons';
  static const String _kFontPkg = 'tiki_sdk_flutter';

  static const IconData x_icon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_icon =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_circle_question =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
